name: solfeggio_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audio_service: ^0.18.0
  just_audio: ^0.9.34
  audioplayers: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/audio/174Hz.mp3
  - assets/audio/285Hz.mp3
  - assets/audio/396Hz.mp3
  - assets/audio/417Hz.mp3
  - assets/audio/528Hz.mp3
  - assets/audio/639Hz.mp3
  - assets/audio/741Hz.mp3
  - assets/audio/852Hz.mp3
  - assets/audio/963Hz.mp3
