flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/audio/174Hz_30min.mp3
    - assets/audio/285Hz_30min.mp3
    - assets/audio/396Hz_30min.mp3
    - assets/audio/417Hz_30min.mp3
    - assets/audio/432Hz_30min.mp3
    - assets/audio/528Hz_30min.mp3
    - assets/audio/639Hz_30min.mp3
    - assets/audio/741Hz_30min.mp3
    - assets/audio/852Hz_30min.mp3
    - assets/audio/963Hz_30min.mp3
